networks:
  quickplay-network:
    driver: bridge

services:
  mongodb:
    container_name: mongodb
    image: "mongo:latest"
    environment:
      - "MONGO_INITDB_DATABASE=mydatabase"
      - "MONGO_INITDB_ROOT_PASSWORD=secret"
      - "MONGO_INITDB_ROOT_USERNAME=root"
    ports:
      - "27017:27017"
    networks:
      - quickplay-network
